/*!CK:2672078903!*//*1375678743,178159149*/

if (self.CavalryLogger) { CavalryLogger.start_js(["v8ZqI"]); }

__d("RefreshableRHCAds",["DOM","Event","SubscriptionsHandler","csx"],function(a,b,c,d,e,f){var g=b('DOM'),h=b('Event'),i=b('SubscriptionsHandler'),j=b('csx'),k,l;function m(o){var p=g.scry(o,"._5f85 a")[0];if(p)l.addSubscriptions(h.listen(p,'click',k));}var n={cleanup:function(){l.release();l=null;},bindLinks:m,init:function(o,p){k=p;l=new i();m(o);}};e.exports=n;});
__d("GroupsMemberCountUpdater",["Arbiter","DOM"],function(a,b,c,d,e,f){var g=b('Arbiter'),h=b('DOM');function i(){}i.subscribeMemberCount=function(j){g.subscribe('GroupsMemberCount/changeText',function(k,l){h.setContent(j,l);});};i.subscribeNewMemberCount=function(j){g.subscribe('GroupsMemberCount/changeNewMembersText',function(k,l){h.setContent(j,l);});};e.exports=i;});
__d("GroupSearchBox",["CSS","DOM","Event","Input","copyProperties"],function(a,b,c,d,e,f){var g=b('CSS'),h=b('DOM'),i=b('Event'),j=b('Input'),k=b('copyProperties'),l={init:function(m,n){var o=h.find(n,'.inputtext');i.listen(m,'click',function(){g.show(n);o.focus();});i.listen(o,'blur',function(){if(!j.getValue(o))g.hide(n);});}};e.exports=l;});
__d("GroupsAddTypeaheadView",["Arbiter","Class","ContextualTypeaheadView","copyProperties"],function(a,b,c,d,e,f){var g=b('Arbiter'),h=b('Class'),i=b('ContextualTypeaheadView'),j=b('copyProperties');function k(l,m){this.parent.construct(this,l,m);}h.extend(k,i);j(k.prototype,{select:function(l){var m=this.results[this.index];g.inform('GroupsMemberSuggestion/remove',m.uid);if(m.is_member){this.reset();}else this.parent.select(l);}});e.exports=k;});
__d("GroupsAddMemberTypeahead",["Arbiter","DOM","Typeahead","copyProperties","ge"],function(a,b,c,d,e,f){var g=b('Arbiter'),h=b('DOM'),i=b('Typeahead'),j=b('copyProperties'),k=b('ge');function l(m,n){if(m&&n)this.init(m,n);}j(l.prototype,{init:function(m,n){m.subscribe('select',function(o,p){g.inform('GroupsAddMemberTypeahead/add',{gid:n,uid:p.selected.uid,name:p.selected.text,photo:p.selected.photo});var q=m.getData().getExclusions();q.push(p.selected.uid);m.getData().setExclusions(q);});g.subscribe('GroupsAddMemberTypeahead/updateGroupToken',this.resetTypeaheadCaches.bind(this));},resetTypeaheadCaches:function(m,n){var o=h.scry(k('pagelet_group_'),'.uiTypeahead:not(.uiPlacesTypeahead)');for(var p=0;p<o.length;p++){var q=i.getInstance(o[p]);if(q){var r=q.getData();r.updateToken(n.token);q.getCore().subscribe('focus',r.bootstrap.bind(r));}}}});e.exports=l;});
__d("legacy:GroupsAddMemberTypeahead",["GroupsAddMemberTypeahead"],function(a,b,c,d){a.GroupsAddMemberTypeahead=b('GroupsAddMemberTypeahead');},3);
__d("HomeRightColumnRemindersController",["Event","LegacyContextualDialog","DOM","Run","throttle"],function(a,b,c,d,e,f){var g=b('Event'),h=b('LegacyContextualDialog'),i=b('DOM'),j=b('Run'),k=b('throttle'),l=[],m;function n(){l.forEach(function(q){q.remove();});l=[];}function o(){for(var q=0;q<m.length;q++){var r=h.getInstance(m[q]);r.hide();}}var p={init:function(){m=i.scry(document,'div.fbRemindersContent');j.onLeave(n);l=[g.listen(window,'resize',k(o)),g.listen(window,'scroll',k(o))];}};e.exports=p;});
__d("RequiredFormListener",["Event","Input"],function(a,b,c,d,e,f){var g=b('Event'),h=b('Input');g.listen(document.documentElement,'submit',function(i){var j=i.getTarget().getElementsByTagName('*');for(var k=0;k<j.length;k++)if(j[k].getAttribute('required')&&h.isEmpty(j[k])){j[k].focus();return false;}},g.Priority.URGENT);});
__d("LitestandRHCAds",["Arbiter","DOM","Event","LitestandMessages","RefreshableRHCAds","Run","SubscriptionsHandler","UIPagelet","copyProperties","csx","debounceAcrossTransitions","ge"],function(a,b,c,d,e,f){var g=b('Arbiter'),h=b('DOM'),i=b('Event'),j=b('LitestandMessages'),k=b('RefreshableRHCAds'),l=b('Run'),m=b('SubscriptionsHandler'),n=b('UIPagelet'),o=b('copyProperties'),p=b('csx'),q=b('debounceAcrossTransitions'),r=b('ge'),s,t,u,v,w,x,y,z;function aa(){var fa=h.scry(u,"div._4u8");for(var ga=0,ha=fa.length;ga<ha;++ga){var ia=JSON.parse(fa[ga].getAttribute('data-ad')).segment;if(ia==='premium')return true;}return false;}function ba(){if(!u)return;var fa=!aa(),ga=Date.now();if(fa&&!x&&v.interval&&ga-s>=v.interval)ca();}function ca(){if(!u)return;s=Date.now();var fa=w&&w.data,ga=o(fa,{ads_only:false,is_litestand:true,organic_only:false,refresh_num:++t});n.loadFromEndpoint('WebEgoPane',u,{dom_id:h.getID(u),pid:w.pid,data:ga},{bundle:false,handler:function(){k.bindLinks(u);}});}function da(){u=null;v=null;w=null;x=false;y.release();y=null;k.cleanup();z.reset();}var ea={init:function(fa,ga,ha){if(!ha||!ha.data||!ha.data.is_litestand)return;u=r(fa);s=Date.now();v=ga;w=ha;t=0;z=q(ba,ga.delay);k.init(u,ca);y=new m();y.addSubscriptions(g.subscribe(j.FILTER_SWITCH_BEGIN,da),g.subscribe(j.NEW_STORY_BAR_CLICK,function(){if(Date.now()-s>ga.new_story_bar_delay_ms)ca();}),i.listen(u,'mouseenter',function(){x=true;}),i.listen(u,'mouseleave',function(){x=false;}),i.listen(window,'scroll',z),i.listen(window,'resize',z));if(ga.onmove)y.addSubscriptions(i.listen(window,'mousemove',z));l.onLeave(da);}};e.exports=ea;});
__d("legacy:LitestandRHCController",["LitestandRHCController"],function(a,b,c,d){a.LitestandRHCController=b('LitestandRHCController');},3);
__d("CovercardArrow",["ContextualDialogArrow","CSS","DOMQuery","Locale","Style","csx","cx"],function(a,b,c,d,e,f){var g=b('ContextualDialogArrow'),h=b('CSS'),i=b('DOMQuery'),j=b('Locale'),k=b('Style'),l=b('csx'),m=b('cx'),n=-45,o=45,p=10;if(j.isRTL()){n=-n;o=-o;}function q(s){this._layer=s;}q.prototype.enable=function(){this._layer.enableBehavior(g);var s=this._layer.getContentRoot();this._arrowWrapper=i.scry(s,"._7lh")[0];if(!this._arrowWrapper)return;this._arrowShadow=i.scry(this._arrowWrapper,"._7li")[0];if(!this._arrowShadow)return;var t=null;if(this._arrowWrapper.style.webkitMaskPosition!==undefined){t=this._renderArrowWithWebkitMask.bind(this);h.addClass(s,"_7ld");}else if(r(this._arrowWrapper)){t=this._renderArrowWithRotate.bind(this);h.addClass(s,"_7le");}if(!t)return;if(j.isRTL())h.addClass(s,"_7lf");this._subscription=this._layer.subscribe('reposition',function(u,v){var w=v.getPosition()=='below';h.conditionClass(s,"_53ih",w);w&&t(v);});};q.prototype.disable=function(){this._subscription&&this._subscription.unsubscribe();this._subscription=null;};q.prototype._calculateArrowOffset=function(s){var t=g.getOffsetPercent(s),u=g.getOffset(s,t,this._layer),v=k.get(this._layer.getContentRoot(),'width');return parseInt(v,10)*(t/100)+u;};q.prototype._renderArrowWithWebkitMask=function(s){var t=g.getOffsetSide(s),u=this._calculateArrowOffset(s);if(j.isRTL()){var v=k.get(this._layer.getContentRoot(),'width');u=parseInt(v,10)-u-this._layer.getArrowDimensions().offset;t=t=='left'?'right':'left';}k.set(this._arrowWrapper,'webkitMaskPositionX',u+'px');k.set(this._arrowShadow,t,u+'px');};q.prototype._renderArrowWithRotate=function(s){var t=i.scry(this._arrowWrapper,"._7lj")[0];if(!t)return;var u=r(this._arrowWrapper);if(!u)return;var v=this._calculateArrowOffset(s),w=p+v;if(j.isRTL())w=-w;this._arrowWrapper.style[u]='translate('+w+'px, -'+p+'px) '+'rotate('+o+'deg)';t.style[u]='rotate('+n+'deg) '+'translate('+(-w)+'px, 0px)';};function r(s){if(!s)s=document.body;var t=['transform','WebkitTransform','msTransform','MozTransform','OTransform'],u;while(u=t.shift())if(s.style[u]!==undefined)return u;return null;}e.exports=q;});
__d("TypeaheadSubmitOnSelect",["Form","copyProperties"],function(a,b,c,d,e,f){var g=b('Form'),h=b('copyProperties');function i(j){this._typeahead=j;}i.prototype.enable=function(){this._subscription=this._typeahead.subscribe('select',function(){var j=this._typeahead.getCore().getElement().form;if(j)j.getAttribute('rel')=='async'?g.bootstrap(j):j.submit();}.bind(this));};i.prototype.disable=function(){this._typeahead.unsubscribe(this._subscription);this._subscription=null;};h(i.prototype,{_subscription:null});e.exports=i;});
__d("legacy:SubmitOnSelectTypeaheadBehavior",["TypeaheadSubmitOnSelect"],function(a,b,c,d){var e=b('TypeaheadSubmitOnSelect');if(!a.TypeaheadBehaviors)a.TypeaheadBehaviors={};a.TypeaheadBehaviors.submitOnSelect=function(f){f.enableBehavior(e);};},3);