(function () {
    'use strict';function C(){return function(){}}
(function(e,h){function q(){var a=arguments.length,c=!1;if(q.e&&a===q.e.length)for(c=!0;a--;)if(q.e[a]!==arguments[a]){c=!1;break}q.e=arguments;c||(m.log.apply(m,arguments),w.send.apply(w,arguments))}function H(){if(!J||z.qa)if(v||z.ba){var a=D.ia(),c=a.length,b;if(0===c)m.log("no new ads found");else{v||(b=1);for(J&&(b=2);c--;)b?w.add_banner(a[c].X,a[c].$,b):w.add_banner(a[c].X,a[c].$);w.send_banners()?m.log("sent"):m.log("couldn't send")}}}function K(a,c){for(var b=0,f=a.length;b<=f;)if(a[b++]===
c)return b-1;return-1}if(!e.__cm){(function(a,c){function b(){}function f(a,b){if(a){"object"===typeof a&&(a=[].slice.call(a));for(var c=0,f=a.length;c<f;c++)b.call(a,a[c],c)}}function d(a,b){var f=Object.prototype.toString.call(b).slice(8,-1);return b!==c&&null!==b&&f===a}function e(a){return d("Function",a)}function g(a){a=a||b;a.da||(a(),a.da=1)}function h(a){var b={};if("object"===typeof a)for(var c in a)a[c]&&(b={name:c,url:a[c]});else b=a.split("/"),b=b[b.length-1],c=b.indexOf("?"),b={name:-1!==
c?b.substring(0,c):b,url:a};return(a=A[b.name])&&a.url===b.url?a:A[b.name]=b}function l(a){a=a||A;for(var b in a)if(a.hasOwnProperty(b)&&a[b].state!==q)return!1;return!0}function m(a,c){c=c||b;a.state===q?c():a.state===w?r.d(a.name,c):a.state===v?a.Z.push(function(){m(a,c)}):(a.state=w,n(a,function(){a.state=q;c();f(s[a.name],function(a){g(a)});B&&l()&&f(s.ca,function(a){g(a)})}))}function n(c,f){f=f||b;var d;/\.css[^\.]*$/.test(c.url)?(d=k.createElement("link"),d.type="text/"+(c.type||"css"),d.rel=
"stylesheet",d.href=c.url):(d=k.createElement("script"),d.type="text/"+(c.type||"javascript"),d.src=c.url);d.onload=d.onreadystatechange=function(b){b=b||a.event;if("load"===b.type||/loaded|complete/.test(d.readyState)&&(!k.documentMode||9>k.documentMode))d.onload=d.onreadystatechange=d.onerror=null,f()};d.onerror=function(){d.onload=d.onreadystatechange=d.onerror=null;f()};d.async=!1;d.defer=!1;var p=k.head||k.getElementsByTagName("head")[0];p.insertBefore(d,p.lastChild)}function u(){k.body?B||(B=
!0,f(y,function(a){g(a)})):(a.clearTimeout(r.G),r.G=a.setTimeout(u,50))}function t(){k.addEventListener?(k.removeEventListener("DOMContentLoaded",t,!1),u()):"complete"===k.readyState&&(k.detachEvent("onreadystatechange",t),u())}var k=a.document,y=[],x=[],s={},A={},F="async"in k.createElement("script")||"MozAppearance"in k.documentElement.style||a.opera,P,B,Q=a.la&&a.la.head||"head",r=a[Q]=a[Q]||function(){r.d.apply(null,arguments)},v=1,w=3,q=4;r.load=F?function(){var a=arguments,b=a[a.length-1],c=
{};e(b)||(b=null);f(a,function(f,d){f!==b&&(f=h(f),c[f.name]=f,m(f,b&&d===a.length-2?function(){l(c)&&g(b)}:null))});return r}:function(){var a=arguments,b=[].slice.call(a,1),d=b[0];if(!P)return x.push(function(){r.load.apply(null,a)}),r;d?(f(b,function(a){if(!e(a)){var b=h(a);b.state===c&&(b.state=v,b.Z=[],n({url:b.url,type:"cache"},function(){b.state=2;f(b.Z,function(a){a.call()})}))}}),m(h(a[0]),e(d)?d:function(){r.load.apply(null,b)})):m(h(a[0]));return r};r.i=r.load;r.test=function(a,c,f,F){a=
"object"===typeof a?a:{test:a,I:c?d("Array",c)?c:[c]:!1,A:f?d("Array",f)?f:[f]:!1,O:F||b};(c=!!a.test)&&a.I?(a.I.push(a.O),r.load.apply(null,a.I)):!c&&a.A?(a.A.push(a.O),r.load.apply(null,a.A)):F();return r};r.d=function(a,b){if(a===k)return B?g(b):y.push(b),r;e(a)&&(b=a,a="ALL");if("string"!==typeof a||!e(b))return r;var c=A[a];if(c&&c.state===q||"ALL"===a&&l()&&B)return g(b),r;(c=s[a])?c.push(b):s[a]=[b];return r};r.d(k,function(){l()&&f(s.ca,function(a){g(a)});r.ga&&r.ga("domloaded",!0)});if("complete"===
k.readyState)u();else if(k.addEventListener)k.addEventListener("DOMContentLoaded",t,!1),a.addEventListener("load",u,!1);else{k.attachEvent("onreadystatechange",t);a.attachEvent("onload",u);var z=!1;try{z=null==a.frameElement&&k.documentElement}catch(D){}z&&z.doScroll&&function S(){if(!B){try{z.doScroll("left")}catch(b){a.clearTimeout(r.G);r.G=a.setTimeout(S,50);return}u()}}()}setTimeout(function(){P=!0;f(x,function(a){a()})},300)})(e);if("undefined"==typeof l){var l=l||{};l.log=l.log||C();l.warn=
l.warn||C();l.error=l.error||C();l.info=l.info||C();l.debug=l.debug||l.log}e.idCoreOnReady=function(a){e.IDCore.onFlashReady(a)};e.tnsOnStatResult=function(a){l.log("result:"+a.result+" pid:"+a.va+" e.id: "+a.id)};var d=d||{};d.random=function(){var a=(new Date).valueOf().toString();return parseInt(a.substr(a.length-8,a.length))+Math.round(Math.random()*Math.pow(10,9))};d.ka=function(){return location.protocol+"//"+("https:"==location.protocol?"sslpagestat.mmi.bemobile.ua":"pagestat.mmi.bemobile.ua")+
"/pagestat/PageStatEntry"};d.ra=function(a,c){return function(){return a.apply(c||e,Array.prototype.slice.call(arguments))}};d.time=function(){return(new Date).getTime()};d.P=function(){var a;try{a=e.XDomainRequest?new e.XDomainRequest:new XMLHttpRequest}catch(c){l.error("cors:"+c)}return a};d.F=function(){return/Mobi|Mini|Symbian|SAMSUNG|Nokia|BlackBerry|Series|Bada|SymbOS|PLAYSTATION/g.test(navigator.userAgent.toString())};d.escape=function(a){return encodeURIComponent(a)};d.b=function(a,c,b){var f=
"&";-1==a.indexOf("?")&&(f="?");return a+(f+c+"="+b)};d.v=function(){for(var a=[],c=0;32>c;c++)a[c]="0123456789ABCDEF".substr(Math.floor(16*Math.random()),1);a[12]="4";a[16]="0123456789ABCDEF".substr(a[16]&3|8,1);return a.join("")};d.r=function(a,c,b){h.cookie=a+"="+escape(c)+(b?"; expires="+b:"")+"; path=/"};d.g=function(a){var c=" "+h.cookie;a=" "+a+"=";var b=null,f=0,d=0;0<c.length&&(f=c.indexOf(a),-1!=f&&(f+=a.length,d=c.indexOf(";",f),-1==d&&(d=c.length),b=unescape(c.substring(f,d))));return b};
var G;try{G="localStorage"in e&&null!==e.localStorage}catch(T){G=!1}d.k=G;d.B=function(){if("undefined"==typeof navigator.plugins||0==navigator.plugins.length)try{return!!new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(a){return!1}else return navigator.plugins["Shockwave Flash"]}();d.D=/MSIE/.test(navigator.userAgent);d.na=/MSIE\ 7/.test(navigator.userAgent);d.w=function(a){h.cookie=a+"=; expires=Thu, 01 Jan 1970 00:00:01 GMT;"};d.m=function(){var a;try{a=h.getElementsByTagName("body")[0]}catch(c){}"undefined"!=
typeof a&&null!=a||"undefined"==typeof h.body||(a=h.body)||l.warn("body is not availible");return a};d.o=function(){var a=navigator.cookieEnabled?!0:!1;"undefined"!=typeof navigator.cookieEnabled||a||(h.cookie="testcookie",a=-1!=h.cookie.indexOf("testcookie")?!0:!1,d.w("testcookie"));return a}();d.ta=function(a){return void 0!==a&&null!=a&&""!=a.replace(/\s/g,"")};d.sa=function(a,c){var b=a;if(0==b.toLowerCase().indexOf("/"))if(c)b=c+b;else{var f=e.location.protocol.toString()+"//"+e.location.hostname.toString()+
e.location.port.toString();""!=f&&(b=f+b)}return d.escape(b)};d.round=function(a){return Math.floor(100*a)/100};d.ua=function(a){try{return Array.prototype.slice.call(a)}catch(c){for(var b=0,f=a.length,d=Array(f);b<f;)d[b]=a[b],b++;return d}};e.IDCore=e.IDCore||function(){function a(){head.i(n+"/id-core/"+u+"/cds.js",function(){try{(new CrossDomainStorage(n,"/id-core/"+u+"/id.html")).requestValue(k.id,function(a,b){g(b)})}catch(a){l.error("cds.js:"+a),s=d.v(),g(s)}})}function c(){var a=new Date;a.setFullYear(a.getFullYear()+
1);d.r(k.wasMigrated,!0,a.toGMTString());g(s)}function b(){return d.g(k.wasMigrated)?!1:d.o&&d.g(k.wasInitialized)?(s=d.g(k.id),d.k?(head.i(n+"/id-core/"+u+"/cds.js",function(){try{(new CrossDomainStorage(n,"/id-core/"+u+"/id.html")).requestValue(k.id+":"+s,function(a,b){b!=s?l.error("id: "+b+" != "+s):c()})}catch(a){l.error("migrate:"+a)}}),d.w(k.id),d.w(k.wasInitialized)):d.B&&(e.tns_uid=s,head.i(n+"/id-core/"+u+"/flash.js",function(){c()})),!0):!1}function f(){y=!0;b()||(d.k?(s=localStorage.getItem(k.id))?
g(s):e.postMessage&&!e.JSON&&e.localStorage?head.i(n+"/json2.min.js",function(){d.m()?a():head.d(function(){a()})}):e.postMessage&&e.JSON&&e.localStorage?d.m()?a():head.d(function(){a()}):g(d.v()):d.B?d.m()?head.i(n+"/id-core/"+u+"/flash.js"):head.d(function(){head.i(n+"/id-core/"+u+"/flash.js")}):((s=d.g(k.id))||(s=d.v()),g(s)))}function p(){for(var a in x)if(x.hasOwnProperty(a)){var b=x[a].url,c=x[a].params,f=x[a].time,d=x[a].type;d&&"POST"==d.toUpperCase()?m(b,c,f):t(b,c,f,d)}x=[];for(var p in A)A.hasOwnProperty(p)&&
A[p].call(this,s);A=[]}function g(a){s=a;if(d.k)localStorage.setItem(k.id,a);else if(d.o){var b=new Date;b.setFullYear(b.getFullYear()+1);d.r(k.id,a,b.toGMTString());d.r(k.wasInitialized,!0,b.toGMTString())}E=!0;p();d.k?localStorage.getItem(k.flag)||((new Image).src=location.protocol+"//juke.mmi.bemobile.ua/bug/pic.gif?uid="+a+"&time="+(new Date).valueOf(),localStorage.setItem(k.flag,"true")):d.o&&!d.g(k.flag)&&(b=new Date,b.setFullYear(b.getFullYear()+1),d.r(k.flag,"true",b.toGMTString()),(new Image).src=
location.protocol+"//juke.mmi.bemobile.ua/bug/pic.gif?uid="+a+"&time="+(new Date).valueOf())}function O(a,b){var c,f;if(b instanceof Array)for(c in b)a=d.b(a,b[c].key,b[c].value);else for(f in b)a=d.b(a,f,b[f]);return a}function m(a,b,c){var f=d.P();f.open("POST",a,!0);b||(b={});b instanceof Array?(b.push({key:"cookie",value:s}),b.push({key:"time",value:c?c:(new Date).valueOf()})):(b.cookie=s,b.time=c?c:(new Date).valueOf());d.D?f.contentType="text/plain":f.setRequestHeader("Content-type","application/x-www-form-urlencoded;charset=UTF-8");
a=O("?",b).replace(/^\?/,"");f.send(a)}function t(a,b,c,f){b||(b={});a=d.b(a,"cookie",s);a=d.b(a,"time",c?c:(new Date).valueOf());a=O(a,b);try{if(f&&"JSONP"==f||e.opera||d.na){var p=h.createElement("script");p.setAttribute("src",a);h.getElementsByTagName("head")[0].appendChild(p)}else{var g=d.P();g.open("GET",a,!0);!1==d.D&&g.setRequestHeader("Accept","application/json");g.send()}}catch(x){l.log(x)}}var E=!1,n=location.protocol+"//source.mmi.bemobile.ua",u="1.53-r43392",v=u.replace(/-r\d+$/,""),k=
{id:"vplayer_user_id",wasInitialized:"tns_was_initialized",wasMigrated:"tns_was_migrated",flag:"flag"},y=!1,x=[],s="",A=[];return{init:function(){!1==y?d.o&&!d.g(k.wasMigrated)?d.m()?f():head.d(function(){f()}):f():E&&p()},send:function(a,b,c){E?c&&"POST"==c.toUpperCase()?m(a,b):t(a,b,(new Date).valueOf(),c):x.push({url:a,params:b,type:c,time:(new Date).valueOf()})},onFlashReady:function(a){try{var b=h.getElementById("div_holder");b.parentNode.removeChild(b)}catch(c){}swfobjectlite=null;g(a)},addOnReadyListener:function(a){A.push(a)},
isReady:function(){return E},getId:function(){return s},version:function(){return v}}}();d=d||{};d.W=function(a,c,b){for(var f=!0,d=0;d<a.length;d++){var e=a[d];e.link==c&&e.pos==b&&(f=!1)}return f};e.IDCore.init();e.TnsId=e.TnsId||function(a){function c(){return!(e.opera||null!=navigator.userAgent.match(/MSIE/)||null!=navigator.userAgent.match(/iPhone\ OS\ 3/))}function b(a,b,c,f){a='{"link":"'+d.escape(a)+'", "pos" :"'+d.escape(b);"undefined"!==typeof c&&c&&(a+='", "sr" : "'+d.escape(c));return a+
'"}'+(f?",":"")}function f(){var a=!0;if(null!==n&&0<n.length){for(var f="[",k=0;k<n.length;k++)f+=b(n[k].link,n[k].pos,n[k].sr,k!=n.length-1);f+="]";try{if(c()){var h=f,m=p();m.param1="~cm_banners~";m.result=h;e.IDCore.send(g,m,"POST")}else h=d.b(g,"param1","~cm_banners~"),h=d.b(h,"result",f),e.IDCore.send(h,p());for(k=0;k<n.length;k++)u.push(n[k]);n=[]}catch(B){a=!1,l.error("post: can't process request "+g+" vars:"+f+" case:"+B)}}return a}function p(){var a=d.escape(e.location.href),b=d.escape(h.referrer),
c=d.B?"1":"0",f=m,p;p=t;""!=v&&(p=v+p);p=p+"/"+e.IDCore.version();a={location:a,referrer:b,is_flash:c,session_id:f,version:p,sw:screen.width,sh:screen.height,scd:screen.colorDepth,js:"1",pid:k++,id:E};!1==d.D&&(a.spd=screen.pixelDepth);try{e.addonCMeter&&e.addonCMeter.PLID&&(a.tnscm_plid=e.addonCMeter.PLID),e.tnscm_cat&&(a.tnscm_cat=e.tnscm_cat),e.tnscm_adn&&(a.tnscm_adn=e.tnscm_adn)}catch(g){l.warn(g)}return a}var g=d.ka(),m=d.random(),t="3.59-r43392".replace(/-r\d+$/,""),v="",E="id_"+d.random(),
n=[],u=[],q=1,k=0,y={init:function(){e.IDCore.init()},send:function(a,b,c,f,k){var h=g;void 0!=a&&(h=d.b(h,"param1",a));void 0!=b&&(h=d.b(h,"param2",b));void 0!=c&&(h=d.b(h,"param3",c));"undefined"!==typeof f&&f&&(h=d.b(h,"param4",f));"undefined"!==typeof k&&k&&(h=d.b(h,"param5",k));e.IDCore.send(h,p())},send_banners:function(){return f()},add_banner:function(a,p,e){null==n&&(n=[]);var g=d.W(n,a,p)&&d.W(u,a,p);if(g){if(!1==c()){for(var k=0,h=0;h<n.length;h++)k+=b(n[h].link,n[h].pos,n[h].sr,h==n.length-
1).length;k+=b(a,p,e,!0).length;3500<=k&&(q=1,f())}a={link:a,pos:p};e&&(a.sr=e);n.push(a)}20<=q?(q=1,f()):++q;return g}};(function(a){void 0!==a&&""!==a&&(v=escape(a));e.IDCore.addOnReadyListener(function(a){l.log("addOnReadyListener:"+a);void 0!==y.onReady&&(d.k&&"initializing"===localStorage.getItem("AddonCMeter")?e.addEventListener("message",function F(a){"AddonCMeterReady"===a.data&&(e.removeEventListener("message",F,!1),y.onReady.call(y,e.IDCore.getId()))},!1):y.onReady.call(y,e.IDCore.getId()))})})(a);
return y};var L={defaults:[[1,"*bdv.bidvertiser.com/bidvertiser.dbm*"],[1,"*squirrelsigdrs.in/banners/show.php*"],[1,"*code.gif*"],[1,"*calend.ru/img/calendar/*"],[1,"*hochu.ua/images/articles/*"],[1,"*tagcloud.swf*"],[1,"*sportingbet-affiliate.host.bannerflow.com*"],[1,"*myinfotopia.com/*"],[1,"*swfhttprequest.swf*"],[1,"*cityads.ru/*"],[1,"*/www/delivery/*"],[1,"*z5x.net/*"],[1,"*adotube.com/*"],[1,"*lux-bn.com.ua/*"],[1,"*criteo.com/*"],[1,"*autocompleteplus.com/*"],[1,"*akamaihd.net/*"],[1,"*etgdta.com*"],
[1,"*soundmanager*.swf*"],[1,"*player.swf*"],[1,"*img.traffim.com/*"],[1,"*sharedaddomain.com/*"],[1,"*avalala.com/*"],[1,"*meta.ua/img/b/roll_flv2.swf*"],[1,"*flowplayer*"],[1,"*manifest.f4m*"],[1,"*logo*"],[1,"*radikal.ru/*"],[1,"*jsonlock.net/*"],[1,"*medbrowse.com.ua/oops*"],[1,"*.yandex.*"],[1,"*uploads/articles/*"],[1,"*proxy.com*"],[1,"*ternopilmarket.net/modules/goods/images/*"],[1,"*proxy*.media.online.ua/*"],[1,"*/picture*_user/*"],[1,"*img*.begun.ru/*"],[1,"*topdownloads.ru/*"],[1,"*gloker.org/upload*"],
[1,"*adnova.ru/*"],[1,"*e-parfum.in.ua/products_image/*"],[1,"*mycdn.me/*"],[1,"*gallery.ru/*"],[1,"*adxpansion.com/*"],[1,"*creoads.com/*"],[1,"*bm.img.com.ua/*"],[1,"*adserver.juicyads.com/*"],[1,"*a.s3.ua/*"],[1,"*kidstaff.net*"],[1,"*counter.png*"],[3,"100x100"],[1,"*google.com.ua*"],[1,"*.rjainc.com/images/uploads/*"],[1,"*apis.google.com*"],[1,"*/widget*/*"],[1,"*googleusercontent.com*"],[1,"*lh*.ggpht.com/*"],[1,"*cdn.adnxs.com*"],[1,"*bs.mybb.ru*"],[1,"*mathtag.com*"],[1,"*kavanga.ru*"],[1,
"*anonymizer.com.ua*"],[1,"*ams*.ib.adnxs.com*"],[1,"*ad.yadro.ru*"],[1,"*/img*/photo*/*"],[1,"*/foto/*"],[1,"*odnoklassniki.*"],[1,"*static/images*"],[1,"*.vk.me/*"],[1,"*rollingstone.com/*"],[1,"*/interview*/*"],[1,"*/post*/*"],[1,"*ads*.contentabc.com/*"],[1,"*ads*.msn.com/*"],[1,"*ads.webmasters.ru/*"],[1,"*ads.vsisumy.com/*"],[1,"*ads.trk4.com/*"],[1,"*ads.trafficjunky.net/*"],[1,"*files/images*"],[1,"*ads.porn*/*"],[1,"*4baby.ua/pictures*"],[1,"*.de/*"],[1,"*/thumb*/*"],[1,"*ad.drugasmuga.com/ban.php*"],
[1,"*/public/images/gallery/*"],[1,"*w*.am15.net/*"],[1,"*imgn.dt00.net/*"],[1,"*lcads.ru/*"],[1,"*gazzete.mk.ua/wp-content/uploads/*"],[1,"*techniks.mk.ua/wp-content/uploads/*"],[1,"*img.terrikon.info/*"],[1,"*img.ria.ua/photos/adv/*"],[1,"*optimizedby.brealtime.com/*"],[1,"*/uploads/posts*"],[1,"*source.mmi.bemobile.ua/video/*"],[1,"*avatar*"],[1,"*pagead2.googlesyndication.com*"],[1,"*.pcads.ru/*"],[1,"*fliphotos.com/*"],[1,"*rand_img.php*"],[1,"*/images_slandocomua/*"],[1,"*chrome-extension:*"],
[1,"*about:blank*"],[1,"*data:*"],[1,"*.imgbb.ru/*"],[1,"*hotline.ua/img/tx/*"],[1,"*gazeta.ua/img/preview/*"],[1,"*www.ex.ua/show/*"],[1,"*4baby.ua/productpicture/*"],[1,"*img.gad.org.ua*"],[1,"*1x1.gif*"],[1,"*vk.jpg*"],[1,"*c.bigmir.net*"],[1,"*adlesse.com*"],[1,"*turzona.com.ua*"],[1,"*kartinka.com.ua*"],[1,"*totoro.com.ua*"],[1,"*tas-ua.toboads.com*"],[1,"*vk.com*"],[1,"*infrm.weather.ua/image/*"],[1,"*maps.googleapis.com*"],[1,"*vk_banner*"],[1,"*googleads.g.doubleclick.net*"],[1,"*plusone.google.com*"],
[1,"*twitter.com*"],[1,"*facebook.com*"],[1,"*captcha*"],[1,"*imgg.dt0*.net/*"],[1,"*adserver.*"],[1,"*adverserve.net*"],[1,"*yield*.com/*"],[1,"*adv.fraza.ua/*"],[1,"*sinoptik.ua/_uploaded_files/??/??/uft_????????????????????????????????.jpg"],[1,"*x.magnet.kiev.ua/www/images/*.*"],[1,"*ads*.com/*"]],"*sport.ua*":[[1,"*sport.ua/images/*"]],"*autocentre.ua*":[[1,"*autocentre.ua/images/*"]],"*terrikon.com*":[[1,"*/fans/*"]],"*kievskaya.com.ua*":[[1,"*image.tsn.ua/*"]],"*mbox2.i.ua*":[[1,"*fsimg.ru/*"]],
"*uaua.info*":[[1,"*/pictures/*"]],"*infohome.com.ua*":[[1,"*articles/*"]],"*telekritika.ua*":[[1,"*telekritika.ua*/imgs/*"],[1,"*telekritika.ua*/images/*"]],"*meteo.ua*":[[1,"*meteo.ua/var/banners/favorites_ua.jpg*"]],"*smartphone.ua*":[[1,"*smartphone.ua/img/*"],[3,"240x400"]],"infohome.com.ua":[[3,"250x250"]],"*ria.ua*":[[1,"*img.ria.ua/photos/auto*"]],"*itc.ua*":[[1,"*itc.ua/files/pic*"],[1,"*wp-content*"]],"*lissod.com.ua*":[[1,"*/st_img/flash/*"]],"*onlinetb.com.ua*":[[3,"200x200"]],"*delo.ua*":[[1,
"*inf.korrespondent.net*"],[1,"*informers.ukr.net*"]],"*sport-express.ua*":[[1,"*sport-express.ua/img/*"]],"*calend.ru*":[[1,"*promo.1000zakazov.ru/*"],[1,"*shkolazhizni.ru/img/adv/*"]],"*bestdroid.ru*":[[1,"*upload*"]],"*hnb.com.ua*":[[1,"*artimage*"]],"*biathlon.com.ua*":[[1,"*img/ministerstvo.gif*"]],"*hotline.ua*":[[3,"120x60"]],"*gazeta.ua*":[[3,"300x240"]],"*mamaclub.ua*":[[3,"300x250"]],"*myradio.ua*":[[3,"300x250"]],"*oceni.ua*":[[3,"250x250"]],"*ava.ua*":[[3,"240x400"]],"*.mob.ua*":[[1,"*images.mob.ua/*"]],
"*games.bigmir.net*":[[1,"*ads.*.*"]],"*connect.ua*":[[3,"300x240"]],"*bilshe.com*":[[1,"*banner*"]],"*realty.mail.ru*":[[1,"*img.pre.realty.mail.ru/*.jpg"]],"*pogoda.mail.ru*":[[1,"*r*.mail.ru/b*.jpg"]],"*cards.mail.ru*":[[1,"*r*.mail.ru/b*.png"]],"*hi-tech.mail.ru*":[[1,"*r*.mail.ru/b*.png"],[1,"*r*.mail.ru/b*.jpg"]],"*otvet.mail.ru*":[[1,"*r*.mail.ru/b*.gif"]],"*health.mail.ru*":[[1,"*r*.mail.ru/b*.gif"],[1,"*r*.mail.ru/b*.jpg"]],"*deti.mail.ru*":[[1,"*r*.mail.ru/b*.jpg"]],"*auto.mail.ru*":[[1,
"*r*.mail.ru/b*.jpg"]],"*mail.ru*":[[1,"*ban.*"],[1,"*/adv/*"]],"cm.mmi.macc.com.ua":[[1,"*.png"]]},M={"*172.16.0.*":[[1,"*.gif*"],[1,"*.png*"],[1,"*.swf*"],[1,"*.jpeg*"],[1,"*.jpg*"]],"*":[[1,"*admixer.net*"],[1,"*servedbyadbutler.com*"],[3,"78x78"],[1,"*uploads.ru/*"],[3,"88x40"],[3,"234x200"],[3,"205x333"],[3,"205x280"],[3,"205x60"],[3,"203x70"],[3,"950x90"],[3,"760x90"],[3,"730x60"],[3,"730x90"],[3,"728x90"],[3,"640x90"],[3,"500x100"],[3,"468x120"],[3,"468x60"],[3,"320x76"],[3,"320x60"],[3,"300x600"],
[3,"300x250"],[3,"300x240"],[3,"285x130"],[3,"250x250"],[3,"240x400"],[3,"240x350"],[3,"240x200"],[3,"240x90"],[3,"234x60"],[3,"230x90"],[3,"230x60"],[3,"180x150"],[3,"160x600"],[3,"160x60"],[3,"150x60"],[3,"120x600"],[3,"120x240"],[3,"120x60"],[1,"*banner*"],[1,"*bb.ru*"],[1,"*bigbn.com.ua*"],[1,"*adriver.ru*"],[1,"*banner.km.ua*"],[1,"*banner.ua*"],[1,"*bannerka.ua*"],[1,"*adx.arip.co.th*"],[1,"*trafic.ro*"],[1,"*targetpoint.com*"],[1,"*espotting.com*"],[1,"*cybermonitor.com*"],[1,"*/*/adfox/*/*.swf*"],
[1,"*rle.ru*"],[1,"*body.imho.ru*"],[1,"*msads.net*"],[1,"*y.ibsys.com*"],[1,"*ip.ro*"],[1,"*www.qksrv.net/*"],[1,"*indieclick.com*"],[1,"*ad6.*.*"],[1,"*updated.com*"],[1,"*ad3.*.*"],[1,"*admanager.persianblog.com*"],[1,"*reclama.*"],[1,"*/ads.pl?*"],[1,"*mastermind.com*"],[1,"*adsoldier.com*"],[1,"*adprojekt.pl*"],[1,"*rate.ru*"],[1,"*xchange.ro*"],[1,"*httpool.com*"],[1,"*sensismediasmart.com.au*"],[1,"*searchbar.us*"],[1,"*cookies.cmpnet.com*"],[1,"*ad7.*.*"],[1,"*focalex.com*"],[1,"*ads7.gamecity.net*"],
[1,"*ad9.*.*"],[1,"*comclick.com*"],[1,"*ad4.*.*"],[1,"http://b.c8.net.ua/*"],[1,"*ad8.*.*"],[1,"*adcorps.com*"],[1,"*adcenter.net*"],[1,"*bbn.img.com.ua*"],[1,"*images.rambler.ru/upl/*"],[1,"*/images/*/*/*/*300x250.*"],[1,"*chestionar.ro*"],[1,"*inc.com*"],[1,"*serving-sys.com*"],[1,"*icplatform.com/static/emarketua/external/sites/emarketua/img/aukro4emarket.png"],[1,"*eyewonder.com*"],[1,"*ab.adpro.com.ua/*/*/*.*"],[1,"*2mdn.net*"],[1,"*images/*/*300x150*.*"],[1,"*baner.*"],[1,"*www.ukr.net/img/karta_t.gif"],
[1,"http://post.rmbn.ru/*"],[1,"*www.ukr.net/img/autos/auto*.jpg"],[1,"*ad5.*.*"],[1,"*/data/enquetes/images/banner_*.*"],[1,"*www.ukr.net/_temp/*/??/??/*.jpg"],[1,"*ad*.bigmir.net*"],[1,"*ad0.*.*"],[1,"*meta.ua/img/*/*_200_300_*href=*"],[1,"*/css/partner-swf/*.*"],[1,"*tbn.ru*"],[1,"*/banners_files/*.*"],[1,"*chicco.com.ua/images/box_stepup.png"],[1,"*celeb.com.ua/*_300.jpg"],[1,"*celeb.com.ua/banner_1000x150.png"],[1,"*adbureau.net*"],[1,"*bnet.aviso.ua/www/images/*.*"],[1,"*b.ex.ua/*/*.swf*"],
[1,"*adbrite.com*"],[1,"*/openx/www/images/*.*"],[1,"*/bnr/*"],[1,"*ban.*"],[1,"*/adban/*/*/*.*"],[1,"*informers.sinoptik.ua*"],[1,"*adnet.com.ua/banners/*/*/*/*.*"],[1,"*rose.ixbt.com*"],[1,"*/adv/*"],[1,"*/pagead/imgad?id=*"],[1,"*/adimage.php*"],[1,"*i.holder.com.ua/*/*/*/*.*"],[1,"*bg.liga.net/www/images/*.*"],[1,"*img.gad.org.ua/*/*.*"],[1,"*/images/*/*/*/*.swf"]],"*besplatka.ua*":[[3,"660x90"]],"*besplatks.ua*":[[3,"300x300"]],"*mail.ru*":[[1,"*r*.mail.ru/b*.gif"],[1,"*r*.mail.ru/b*.png"],[1,
"*r*.mail.ru/b*.jpg"],[1,"*r*.mail.ru/b*.swf"],[1,"*promoblocks.ru*"]],"*magnolia-tv.com*":[[3,"300x100"],[3,"218x100"],[3,"100x100"]],"*ex.ua*":[[1,"*ad_click*"]],"cm.mmi.macc.com.ua":[[3,"100x100"]]},z={N:{width:50,height:40},n:[5,15,30,60,120],ha:5,stop:5,ea:5,qa:!0,ba:!0},v,J=e.top!==e.self;G=new Date;var m={log:function(){var a;"undefined"!==typeof l&&("undefined"!==typeof l.debug?a=function(){l.debug([].join.call(arguments," "))}:"undefined"!==typeof l.log&&(a=function(){l.log([].join.call(arguments,
" "))}));return a||C()}(),fa:function(a,c){if("string"!==typeof a)return a;c=c||h;if(0===a.indexOf("http"))return a;var b=h.getElementsByTagName("base"),f=null;if(0<b.length)return 0===a.indexOf("/")&&(a=a.substring(1)),f=b[0].href,"/"!==f.charAt(f.length-1)&&(f+="/"),f+a;var f=c.location,b=f.protocol,d=f.pathname;0!==a.indexOf("//")&&(b+="//"+f.hostname,"/"!==a.charAt(0)&&(0===a.indexOf("./")&&(a=a.substring(2)),"/"!==d.charAt(d.length-1)&&(d=d.substr(0,d.lastIndexOf("/"))),b+=d,"/"!==d.charAt(d.length-
1)&&(b+="/")));return b+a},F:function(){for(var a="Mobi Mini Symbian SAMSUNG Nokia BlackBerry Series Bada SymbOS PLAYSTATION".split(" "),c=a.length;c--;)if(RegExp(a[c],"i").test(navigator.userAgent))return!0;return!1}(),data:function(){function a(a,c){return c.toUpperCase()}var c=/\-([a-z])/ig;return function(b,f,d){if("undefined"===typeof d)return b.u[("data-"+f).replace(c,a)];"undefined"===typeof b.u&&(b.u={});b.u[("data-"+f).replace(c,a)]=d}}(),p:function(){return"addEventListener"in e?function(a,
c,b){a.addEventListener(c,b,!1)}:"attachEvent"in h?function(a,c,b){a.attachEvent("on"+c,b)}:function(a,c,b){a["on"+c]=b}}(),H:function(a,c,b){return a.split(c).join(b)},Y:function(a){for(var c="#|()[]{}^$+.".split(""),b=c.length;b--;)a=m.H(a,c[b],"\\"+c[b]);a=m.H(a,"*",".*");a=m.H(a,"?",".");return"^"+a+"$"}},I=function(){function a(){var a,c=b.length,d=new Date;I=function(a){"function"===typeof a&&a()};for(a=0;a<c;a+=1)b[a](d);I.R=C()}function c(a){"function"===typeof a&&b.push(a)}var b=[];c.R=a;
m.p(e,"load",a);return c}(),t=function(){var a=z,c=function(){return function(a){var c,d=[];a.defaults&&(d=a.defaults);for(c in a)"defaults"!==c&&(a.hasOwnProperty(c)&&RegExp(m.Y(c)).test(location.host))&&(d=d.concat(a[c]));a=d;var e,d=a.length,g=[];for(c=0;c<d;c++)switch(e=a[c],e[0]){case 3:e=e[1].split("x");g.push([3,e[0],e[1]]);break;case 1:g.push([1,RegExp(m.Y(e[1]))]);break;default:g.push(e)}return g}}();M=c(M);L=c(L);(function(a){var c,d=a.n,e=d.length;if(1>e||m.F)a.n=[];else for(c=0;c<e;c+=
1)if(0>d[c]||0<c&&d[c-1]>=d[c]){a.n=[];break}})(a);a.stop*=60;return a}(),w=new TnsId("cm2.2.300/"),R=[],D={j:[],aa:[],ia:function(){for(var a=[],c,b=this.j,d=b.length;d--;){var e=m.data(b[d],"src");if(this.oa(b[d]))c=this.T(b[d]).top+this.U(b[d]).height;else{if(-1===K(R,b[d])){R.push(b[d]);continue}c=-1}a.push({X:e,$:c});this.aa.push(b.splice(d,1)[0])}return a},s:null,V:function(a,c){var b;return h.defaultView&&h.defaultView.getComputedStyle?(c=c.replace(/([A-Z])/g,"-$1").toLowerCase(),(b=h.defaultView.getComputedStyle(a,
null))&&b.getPropertyValue(c)):a.currentStyle?a.currentStyle[c]:a.style&&a.style[c]?a.style[c]:null},T:function(a){if(!a)return{top:0,left:0};var c={top:a.offsetTop,left:a.offsetLeft};a=this.T(a.offsetParent);c.top+=a.top;c.left+=a.left;return c},U:function(a){var c={width:["paddingLeft","paddingRight","borderLeftWidth","borderRightWidth"],height:["paddingTop","paddingBottom","borderTopWidth","borderBottomWidth"]},b={width:a.offsetWidth,height:a.offsetHeight},d,e;for(d in b)if(b.hasOwnProperty(d)){if(0<
b[d])for(e=c[d].length;e--;)b[d]-=parseInt(this.V(a,c[d][e]),10)||0;b[d]=parseInt(b[d]||this.V(a,d),10)}return b},oa:function(a){for(var c=!1,b=a.getClientRects(),d=b.length;d--;)if(a=b[d],0!==a.width&&0!==a.height){if(0<a.top)return a.top<=t.l;if(0<a.bottom)return a.bottom<=t.l;c=!0}return c},ma:function(a){var c=a.getAttribute("src")||"",b=c.indexOf("//"+e.location.host),d;if(0!==c.indexOf("http")&&0!==c.indexOf("//")||-1<b&&8>b)try{if((d=this.S(a))&&d.getElementById)return!0}catch(g){}return!1},
S:function(a){return a.contentDocument||a.contentWindow&&a.contentWindow.document||a.document||null},ja:function(a){var c,b,d;if("undefined"===typeof a.tagName)return!1;if("OBJECT"===a.tagName){if(c=a.getAttribute("data"),!c)for(b=a.childNodes,a=b.length;a--;)if(d=b[a],"PARAM"===d.nodeName&&"movie"===d.getAttribute("name"))return d.getAttribute("value")}else c=a.getAttribute("src");return c},filter:function(){function a(a,b,d){for(var e,g=d.length;g--;)switch(e=d[g],e[0]){case 1:if(e[1].test(a))return[!0,
e];break;case 3:if(b.width==e[1]&&b.height==e[2])return[!0,e]}return[!1]}return function(c){var b=this.U(c),d,e=this.ja(c);if(!e)return!1;e=m.fa(e);if(b.width<=t.N.width||b.height<=t.N.height)return!1;d=a(e,b,M);return!0!==d[0]||a(e,b,L)[0]?!1:(m.data(c,"src",e),m.data(c,"ad-template",d[1]),!0)}}(),K:function(a){function c(a){var c,d;b.filter(a)&&(c=K(b.aa,a),d=K(b.j,a),-1<c||-1<d||b.j.push(a))}for(var b=this,d=["img","embed","object"],e,g=d.length,h;g--;)for(e=a.getElementsByTagName(d[g]),h=e.length;h--;)c(e[h]);
e=a.getElementsByTagName("iframe");for(h=e.length;h--;)a=e[h],this.ma(a)?this.K(this.S(a)):c(a)},parse:function(){this.K(h);0<this.j.length&&this.j.length!==this.pa&&(this.pa=this.j.length,H())},start:function(){var a=this;m.log("parser init");this.stop();this.s=setInterval(function(){a.parse()},1E3*z.ea);this.parse();return this},stop:function(){this.s&&clearInterval(this.s)}},g={c:{start:G,h:new Date,d:null},t:!1,maxHeight:0,a:function(){if(!J){var a=new Date;g.a.e=g.a.e||0;g.a.f[1]=g.a.M||Math.round((a-
(g.c.L||g.c.start))/1E3);g.a.f[2]=g.maxHeight;g.a.f[4]=Math.round((a.getTime()-g.c.start.getTime())/1E3);Math.round((a-g.a.e)/1E3)>=t.ha&&(g.a.e=a,q.apply(N,g.a.f))}},q:function(){var a=0,c=h.body,b=h.documentElement;"number"===typeof e.pageYOffset?a=e.pageYOffset:b&&"undefined"!==typeof b.scrollTop?a=b.scrollTop:c&&"undefined"!==typeof c.scrollTop&&(a=c.scrollTop);t.l=Math.max(b.scrollHeight,b.offsetHeight,b.clientHeight);t.J="clientHeight"in b?b.clientHeight:1;c&&(t.l=Math.max(t.l,c.scrollHeight,
c.offsetHeight,c.clientHeight),t.J="CSS1Compat"===h.compatMode?b.clientHeight:c.clientHeight);a+t.J>g.maxHeight&&(g.maxHeight=a+t.J,g.t=!0)},h:function(){g.c.h=new Date;if(e.performance){var a=performance.timing.navigationStart||performance.timing.connectStart;a<g.c.start&&(g.c.start=new Date(a))}g.h=g.q;setInterval(function(){g.t&&v&&(g.t=!1,g.a())},5E3);return this}};g.a.f=["~cm_timer~",null,null];I(function(a){g.c.d=a;g.a.f[3]=a-g.c.start});m.p(e,"scroll",g.q);m.p(e,"resize",g.q);var N={h:function(){var a=
!1;g.q();w.onReady=function(){function c(){function a(){q||(a.C=a.C||1,a.C++,d(),a.C>=e&&(q=setInterval(d,1E3*(b[e-1]-b[e-2]))))}var b=t.n,e=b.length,h,l=0;c.Q=c.Q||new Date;w||(D.start(),w=setInterval(H,m.F?1E4:5E3),H());if(v&&(g.h(),g.c.L=g.c.L||new Date,0!==e)){1===e&&(q=setInterval(d,1E3*b[0]));2===e&&(q=setInterval(d,1E3*(b[1]-b[0])),setTimeout(d,1E3*b[0]));if(2<e)for(h=0;h<e-1;h++)l=1E3*b[h],setTimeout(a,l);d()}}function b(){m.log("document is",h[e]);"hidden"===h[e]?(d(),H(),q&&clearInterval(q),
q=!1,g.a.M=g.a.M||g.a.f[1],v=!1,D.stop()):(v=!0,c())}function d(){if(v||z.ba)Math.round((new Date-c.Q)/1E3)>=t.stop&&(D.stop(),w&&clearInterval(w),w=!1,q&&clearInterval(q),q=!1),D.parse(),g.a()}var e,l,q,w;a||(a=!0,m.log("id ready"),"undefined"!==typeof h.visibilityState?(e="visibilityState",l="visibilitychange"):"undefined"!==typeof h.mozVisibilityState?(e="mozVisibilityState",l="mozvisibilitychange"):"undefined"!==typeof h.webkitVisibilityState?(e="webkitVisibilityState",l="webkitvisibilitychange"):
"undefined"!==typeof h.msVisibilityState&&(e="msVisibilityState",l="msvisibilitychange"),"undefined"===typeof e?v=!0:("hidden"===h[e]?v=!1:b(),m.p(h,l,b)),c())};w.init();return this}};N.h();e.__cm=N;h.readyState&&"complete"===h.readyState&&I.R()}})(window,document);

}());